INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'HDHE 취향 영화 리뷰', '이 영화는 HDHE 취향을 위한 최고의 선택입니다.', 15, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'VDSE 취향을 위한 추천', 'VDSE 취향을 가진 사람들에게 적합한 영화입니다.', 20, SYSDATE, 'Y', 10002, 20, 2);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'SPTF와 함께하는 감상', 'SPTF 취향 영화 감상 소감입니다.', 5, SYSDATE, 'Y', 10003, 30, 3);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'BOFA 취향 영화', 'BOFA 취향을 위한 영화 리스트.', 30, SYSDATE, 'Y', 10004, 40, 4);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'ETRF 취향의 명작', 'ETRF 취향에 꼭 맞는 영화입니다.', 25, SYSDATE, 'Y', 10005, 50, 5);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CCFE 취향 영화 추천', 'CCFE 취향을 위한 영화 리뷰입니다.', 8, SYSDATE, 'Y', 10006, 60, 6);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CAES를 위한 영화', 'CAES 취향에 맞는 영화 감상 후기.', 12, SYSDATE, 'Y', 10007, 70, 7);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'HHAL 취향 영화 리뷰', 'HHAL 취향을 위한 영화 소개입니다.', 18, SYSDATE, 'Y', 10008, 80, 8);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'HDHE 취향 모음', 'HDHE 취향 영화를 모아서 소개합니다.', 11, SYSDATE, 'Y', 10001, 10, 9);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'VDSE 영화 분석', 'VDSE 취향 영화를 분석해보았습니다.', 22, SYSDATE, 'Y', 10002, 20, 10);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'SPTF 취향 감상기', 'SPTF 취향 영화 감상기입니다.', 14, SYSDATE, 'Y', 10003, 30, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'BOFA 영화 추천', 'BOFA 취향에 맞는 영화 리스트입니다.', 6, SYSDATE, 'Y', 10004, 40, 2);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'ETRF 영화 감상', 'ETRF 취향의 영화를 감상한 소감입니다.', 17, SYSDATE, 'Y', 10005, 50, 3);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CCFE 추천 영화', 'CCFE 취향을 가진 분들께 추천하는 영화.', 19, SYSDATE, 'Y', 10006, 60, 4);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CAES 취향 소개', 'CAES 취향 영화를 소개합니다.', 9, SYSDATE, 'Y', 10007, 70, 5);




INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '내가 좋아하는 영화', '이 영화는 정말 재밌어요!', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '최고의 액션 영화', '이 액션 영화는 놀라운 장면이 가득해요!', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '로맨스 영화 추천', '이 로맨스 영화는 사랑에 관한 깊은 이야기를 담고 있어요.', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '가장 감동적인 영화', '이 영화는 항상 눈물을 흘리게 해요!', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'SF 영화 추천', '이 SF 영화는 미래를 탐험하는 재미가 있어요!', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CCFE 추천 영화', 'CCFE 취향을 가진 분들께 추천하는 영화.', 19, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, 'CAES 취향 소개', 'CAES 취향 영화를 소개합니다.', 9, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '가족 영화 추천', '가족과 함께 보기 좋은 영화입니다.', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '스릴러 영화 분석', '이 스릴러 영화는 긴장감이 최고예요.', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '전쟁 영화 추천', '이 전쟁 영화는 역사를 잘 보여줍니다.', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '다큐멘터리 영화 추천', '이 다큐멘터리는 매우 교육적이에요.', 0, SYSDATE, 'Y', 10001, 10, 1);

INSERT INTO BOARD (BOARD_NO, BOARD_TYPE, BOARD_TITLE, BOARD_CONTENT, BOARD_COUNT, REGIST_DATE, STATUS, USER_NO, TASTE_NO, MOVIE_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, 1, '고전 영화 추천', '이 고전 영화는 모든 사람이 봐야 해요.', 0, SYSDATE, 'Y', 10001, 10, 1);


COMMIT;