INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TEAM_NO) 
VALUES(1, 'admin01', '1234', '010-1234-1234', 'admin01@naver.com', 'admin01', DEFAULT, DEFAULT, 'A', 1);
INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TEAM_NO) 
VALUES(2, 'admin01', '1234', '010-2345-6789', 'admin02@naver.com', 'admin02', DEFAULT, DEFAULT, 'A', 2);
INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TEAM_NO) 
VALUES(3, 'admin01', '1234', '010-3456-7891', 'admin03@naver.com', 'admin03', DEFAULT, DEFAULT, 'A', 3);
INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TEAM_NO) 
VALUES(4, 'admin01', '1234', '010-4567-8912', 'admin04@naver.com', 'admin04', DEFAULT, DEFAULT, 'A', 4);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user01', '1234', '010-1111-1111', 'user01@naver.com', 'user01', DEFAULT, DEFAULT, DEFAULT, 10);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user02', '1234', '010-2222-2222', 'user02@naver.com', 'user02', DEFAULT, DEFAULT, DEFAULT, 20);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user03', '1234', '010-3333-3333', 'user03@naver.com', 'user03', DEFAULT, DEFAULT, DEFAULT, 30);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user04', '1234', '010-4444-4444', 'user04@naver.com', 'user04', DEFAULT, DEFAULT, DEFAULT, 40);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user05', '1234', '010-5555-5555', 'user05@naver.com', 'user05', DEFAULT, DEFAULT, DEFAULT, 50);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user06', '1234', '010-6666-6666', 'user06@naver.com', 'user06', DEFAULT, DEFAULT, DEFAULT, 60);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user07', '1234', '010-7777-7777', 'user07@naver.com', 'user07', DEFAULT, DEFAULT, DEFAULT, 70);

INSERT INTO USERS(USER_NO, USER_ID, USER_PWD, PHONE, EMAIL, USER_NICKNAME, ENROLL_DATE, MODIFY_DATE, STATUS, TASTE_NO) 
VALUES(SEQ_USERNO.NEXTVAL, 'user08', '1234', '010-8888-8888', 'user08@naver.com', 'user08', DEFAULT, DEFAULT, DEFAULT, 80);

COMMIT;
