INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '배송 문의', '제품이 언제 도착하나요?', '배송', SYSDATE, 'Y', 10001, '제품은 3일 내로 도착할 예정입니다.', 'admin01', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '결제 문의', '결제가 안됩니다.', '결제', SYSDATE, 'Y', 10002, '결제 오류가 확인되었습니다. 해결 중입니다.', 'admin02', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '환불 문의', '환불 요청드립니다.', '환불', SYSDATE, 'Y', 10003, '환불 요청이 처리되었습니다.', 'admin03', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '교환 요청', '제품을 교환하고 싶습니다.', '교환', SYSDATE, 'Y', 10004, '교환 절차를 안내드렸습니다.', 'admin01', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '상품 문의', '이 제품의 재입고 일정은 언제인가요?', '상품', SYSDATE, 'Y', 10005, '재입고 일정은 미정입니다.', 'admin02', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '계정 문의', '비밀번호를 잊어버렸습니다.', '계정', SYSDATE, 'Y', 10006, '비밀번호 재설정 안내를 드렸습니다.', 'admin03', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '배송 오류', '제품이 잘못 배송되었습니다.', '배송', SYSDATE, 'Y', 10007, '오배송 처리 중입니다.', 'admin01', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '쿠폰 사용', '쿠폰 사용이 안됩니다.', '쿠폰', SYSDATE, 'Y', 10008, '쿠폰 사용법을 안내해 드렸습니다.', 'admin02', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '회원 정보 변경', '이메일 주소를 변경하고 싶습니다.', '회원정보', SYSDATE, 'Y', 10001, '이메일 변경 처리가 완료되었습니다.', 'admin03', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '배송 상태', '주문한 제품의 배송 상태가 궁금합니다.', '배송', SYSDATE, 'Y', 10002, '현재 배송 중입니다.', 'admin01', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '결제 확인', '결제가 정상적으로 완료되지 않았습니다.', '결제', SYSDATE, 'Y', 10001, '결제가 정상적으로 완료되었습니다.', 'admin02', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '상품 문의', '이 제품의 성능에 대해 궁금합니다.', '상품', SYSDATE, 'Y', 10002, '성능에 대해 자세히 안내드렸습니다.', 'admin03', SYSDATE);

INSERT INTO INQUIRY_BOARD (
    INQUIRY_NO, INQUIRY_TITLE, INQUIRY_CONTENT, INQUIRY_TYPE, REGIST_DATE, STATUS, USER_NO, REPLY_CONTENT, USER_NICKNAME, REPLY_DATE
) VALUES (SEQ_INQUIRYNO.NEXTVAL, '배송지 변경', '배송지를 변경하고 싶습니다.', '배송', SYSDATE, 'Y', 10003, '배송지 변경이 완료되었습니다.', 'admin01', SYSDATE);

commit;