-- 더미 데이터 삽입 예시
INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '첫 번째 공지사항', '첫 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '두 번째 공지사항', '두 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 2);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '세 번째 공지사항', '세 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 3);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '네 번째 공지사항', '네 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 4);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '다섯 번째 공지사항', '다섯 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '여섯 번째 공지사항', '여섯 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '일곱 번째 공지사항', '일곱 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '여덟 번째 공지사항', '여덟 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '아홉 번째 공지사항', '아홉 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '열 번째 공지사항', '열 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '열 한 번째 공지사항', '열 한 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '열 두 번째 공지사항', '열 두 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

INSERT INTO NOTICE (NOTICE_NO, NOTICE_TITLE, NOTICE_CONTENT, REGIST_DATE, STATUS, USER_NO) 
VALUES (SEQ_BOARDNO.NEXTVAL, '열 세 번째 공지사항', '열 세 번째 공지사항의 내용입니다.', SYSDATE, 'Y', 1);

COMMIT;
