INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '회원 가입 방법', '회원 가입은 이메일 인증을 통해 간단하게 할 수 있습니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '로그인 오류', '로그인 시 비밀번호가 맞지 않으면 "비밀번호 찾기" 기능을 이용해 주세요.', SYSDATE, 'Y', 2);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '비밀번호 변경', '비밀번호는 마이페이지에서 언제든지 변경하실 수 있습니다.', SYSDATE, 'Y', 3);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '계정 잠금 해제', '계정이 잠긴 경우 고객센터에 문의하시면 신속히 처리해드립니다.', SYSDATE, 'Y', 4);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '회원 탈퇴 방법', '회원 탈퇴는 설정 메뉴에서 직접 처리하실 수 있습니다.', SYSDATE, 'N', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '이메일 변경', '이메일 주소 변경은 고객센터에 문의해 주세요.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '프로필 사진 변경', '프로필 사진은 마이페이지에서 수정 가능합니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '2단계 인증 설정', '2단계 인증을 설정하면 보안이 강화됩니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '결제 수단 추가', '결제 수단은 마이페이지에서 추가할 수 있습니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '쿠폰 사용 방법', '쿠폰은 결제 페이지에서 입력 후 적용할 수 있습니다.', SYSDATE, 'N', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '배송 조회', '주문한 상품의 배송 상태는 마이페이지에서 확인 가능합니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '주문 취소 방법', '주문 취소는 결제 완료 전까지 가능합니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '환불 절차', '환불 요청은 결제 후 7일 이내에 가능합니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '리뷰 작성 방법', '상품 구매 후 마이페이지에서 리뷰를 작성할 수 있습니다.', SYSDATE, 'Y', 1);

INSERT INTO FAQ (FAQ_NO, FAQ_TITLE, FAQ_CONTENT, REGIST_DATE, STATUS, USER_NO)
VALUES (SEQ_FAQNO.NEXTVAL, '상품 교환', '상품 교환 요청은 배송 완료 후 3일 이내 가능합니다.', SYSDATE, 'Y', 1);

COMMIT;