INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Amazing movie! The direction was fantastic.', 5, 10001, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'The plot was good but a bit slow at times.', 4, 10002, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'I didn’t enjoy the movie that much. Too predictable.', 2, 10003, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'An absolute masterpiece. Highly recommend!', 5, 10004, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Not bad, but could have been better.', 3, 10001, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Good performances but the story lacked depth.', 4, 10002, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'A decent watch but wouldn’t watch it again.', 3, 10003, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Simply incredible! One of the best movies this year.', 5, 10004, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'The movie was fine, but not my style.', 3, 10001, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'The action scenes were great, but the plot was weak.', 4, 10002, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Really boring. I almost fell asleep.', 1, 10003, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'I loved every moment of this film!', 5, 10004, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'A solid movie, but nothing groundbreaking.', 4, 10001, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'The storyline was too predictable for my liking.', 2, 10002, 1, SYSDATE);

INSERT INTO REVIEW (REVIEW_NO, REVIEW_CONTENT, GRADE, USER_NO, MOVIE_NO, REVIEW_DATE)
VALUES (SEQ_REVIEWNO.NEXTVAL, 'Great performances, but the story fell flat.', 3, 10003, 1, SYSDATE);

COMMIT