INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 1', SYSDATE, 'Y', 10001, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 2', SYSDATE, 'Y', 10002, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 3', SYSDATE, 'Y', 10003, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 4', SYSDATE, 'Y', 10004, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 5', SYSDATE, 'Y', 10005, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 6', SYSDATE, 'Y', 10006, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 7', SYSDATE, 'Y', 10007, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 8', SYSDATE, 'Y', 10008, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 9', SYSDATE, 'Y', 10009, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 10', SYSDATE, 'Y', 10010, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 11', SYSDATE, 'Y', 10001, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 12', SYSDATE, 'Y', 10002, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 13', SYSDATE, 'Y', 10003, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 14', SYSDATE, 'Y', 10004, 50);

INSERT INTO REPLY (REPLY_NO, REPLY_CONTENT, REGIST_DATE, STATUS, USER_NO, BOARD_NO)
VALUES (SEQ_REPLYNO.NEXTVAL, '댓글 내용 15', SYSDATE, 'Y', 10005, 50);
COMMIT;